[package]
name = "extract_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
color-eyre = "0.6.2"
crossterm = "0.27.0"
eyre = "0.6.8"
indicatif = "0.17.6"
rayon = "1.7.0"
